CREATE TABLE tbl_user
(
    id             NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    first_name     VARCHAR2(255 CHAR) NOT NULL,
    last_name      VARCHAR2(255 CHAR) NOT NULL,
    date_of_birth  DATE,
    gender         VARCHAR2(50 CHAR) DEFAULT 'OTHER' NOT NULL,
    phone          VARCHAR2(50 CHAR),
    email          VARCHAR2(255 CHAR) NOT NULL,
    username       VARCHAR2(255 CHAR) NOT NULL,
    password       VARCHAR2(255 CHAR),
    status         VARCHAR2(50 CHAR) DEFAULT 'NONE' NOT NULL,
    user_type      VARCHAR2(50 CHAR) NOT NULL,
    created_at     TIMESTAMP(6) DEFAULT LOCALTIMESTAMP NOT NULL,
    updated_at     TIMESTAMP(6) DEFAULT LOCALTIMESTAMP NOT NULL,

    CONSTRAINT uq_tbl_user_email UNIQUE (email),
    CONSTRAINT uq_tbl_user_username UNIQUE (username),
    CONSTRAINT ck_tbl_user_gender
        CHECK (gender IN ('MALE', 'FEMALE', 'OTHER')),
    CONSTRAINT ck_tbl_user_status
        CHECK (status IN ('NONE', 'ACTIVE', 'INACTIVE')),
    CONSTRAINT ck_tbl_user_user_type
        CHECK (user_type IN ('OWNER', 'ADMIN', 'USER'))
);

CREATE TABLE tbl_role
(
    id    NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name  VARCHAR2(100 CHAR) NOT NULL,
    created_at     TIMESTAMP(6) DEFAULT LOCALTIMESTAMP NOT NULL,
    updated_at     TIMESTAMP(6) DEFAULT LOCALTIMESTAMP NOT NULL,

    CONSTRAINT uq_tbl_role_name UNIQUE (name)
);

CREATE TABLE tbl_permission
(
    id    NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name  VARCHAR2(100 CHAR) NOT NULL,
    created_at     TIMESTAMP(6) DEFAULT LOCALTIMESTAMP NOT NULL,
    updated_at     TIMESTAMP(6) DEFAULT LOCALTIMESTAMP NOT NULL,

    CONSTRAINT uq_tbl_permission_name UNIQUE (name)
);

CREATE TABLE tbl_user_has_role
(
    id       NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id  NUMBER(19) NOT NULL,
    role_id  NUMBER(19) NOT NULL,
    created_at     TIMESTAMP(6) DEFAULT LOCALTIMESTAMP NOT NULL,
    updated_at     TIMESTAMP(6) DEFAULT LOCALTIMESTAMP NOT NULL,

    CONSTRAINT fk_user_role_user
        FOREIGN KEY (user_id)
            REFERENCES tbl_user (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_user_role_role
        FOREIGN KEY (role_id)
            REFERENCES tbl_role (id)
            ON DELETE CASCADE,

    CONSTRAINT uq_user_role UNIQUE (user_id, role_id)
);

CREATE TABLE tbl_role_has_permission
(
    id             NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    role_id        NUMBER(19) NOT NULL,
    permission_id  NUMBER(19) NOT NULL,
    created_at     TIMESTAMP(6) DEFAULT LOCALTIMESTAMP NOT NULL,
    updated_at     TIMESTAMP(6) DEFAULT LOCALTIMESTAMP NOT NULL,

    CONSTRAINT fk_role_permission_role
        FOREIGN KEY (role_id)
            REFERENCES tbl_role (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_role_permission_permission
        FOREIGN KEY (permission_id)
            REFERENCES tbl_permission (id)
            ON DELETE CASCADE,

    CONSTRAINT uq_role_permission UNIQUE (role_id, permission_id)
);

CREATE TABLE tbl_token
(
    id             NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id        NUMBER(19) NOT NULL,
    access_token   CLOB NOT NULL,
    refresh_token  CLOB,
    created_at     TIMESTAMP(6) DEFAULT LOCALTIMESTAMP NOT NULL,
    updated_at     TIMESTAMP(6) DEFAULT LOCALTIMESTAMP NOT NULL,

    CONSTRAINT fk_token_user
        FOREIGN KEY (user_id)
            REFERENCES tbl_user (id)
            ON DELETE CASCADE
);

-- ======================================

CREATE SEQUENCE TBL_ACCOUNT_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE tbl_account (
    id             NUMBER(19) DEFAULT TBL_ACCOUNT_SEQ.NEXTVAL PRIMARY KEY,
    account_number VARCHAR2(50 CHAR) NOT NULL UNIQUE,
    owner_name     VARCHAR2(255 CHAR) NOT NULL,
    balance        NUMBER(19, 2) NOT NULL,
    status         VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    created_at     TIMESTAMP(6) DEFAULT LOCALTIMESTAMP NOT NULL,
    updated_at     TIMESTAMP(6) DEFAULT LOCALTIMESTAMP NOT NULL,

    CONSTRAINT ck_account_status CHECK (status IN ('ACTIVE', 'BLOCKED'))
);

CREATE SEQUENCE TBL_TRANSACTION_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE tbl_transaction (
    id              NUMBER(19) DEFAULT TBL_TRANSACTION_SEQ.NEXTVAL PRIMARY KEY,
    from_account_id NUMBER(19) NOT NULL,
    to_account_id   NUMBER(19) NOT NULL,
    amount          NUMBER(19, 2) NOT NULL,
    status          VARCHAR2(20 CHAR) DEFAULT 'PENDING' NOT NULL,
    request_id      VARCHAR2(100 CHAR),
    created_at      TIMESTAMP(6) DEFAULT LOCALTIMESTAMP NOT NULL,

    CONSTRAINT fk_txn_from_account
        FOREIGN KEY (from_account_id)
            REFERENCES tbl_account (id),

    CONSTRAINT fk_txn_to_account
        FOREIGN KEY (to_account_id)
            REFERENCES tbl_account (id),

    CONSTRAINT uq_txn_request_id UNIQUE (request_id),
    CONSTRAINT ck_txn_status CHECK (status IN ('PENDING', 'SUCCESS', 'FAILED'))
);
