-- Bang 1: Yeu cau chuyen tien phia App
-- Luu lai moi lan client gui lenh chuyen tien
CREATE TABLE APP_TRANSFER_REQUEST (
    id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_ref     CHAR(16)       NOT NULL,
    idempotency_key  VARCHAR2(128)  NOT NULL,
    debit_account_no VARCHAR2(20)   NOT NULL,
    amount           NUMBER(19, 2)  NOT NULL,
    status           VARCHAR2(30)   NOT NULL,
    created_at       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT uq_app_transfer_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT ck_app_transfer_status CHECK (status IN ('PROCESSING', 'SUCCESS', 'FAILED')),
    CONSTRAINT ck_app_transfer_amount CHECK (amount > 0)
);

COMMENT ON TABLE APP_TRANSFER_REQUEST IS 'Bang luu yeu cau chuyen tien phia ung dung (App-side transfer request)';
COMMENT ON COLUMN APP_TRANSFER_REQUEST.id IS 'Khoa chinh, tu tang (Primary key, auto-increment)';
COMMENT ON COLUMN APP_TRANSFER_REQUEST.external_ref IS 'Ma tham chieu tu doi tac/kenh gui. Dung CHAR(16) co tinh de tao bug padding khoang trang';
COMMENT ON COLUMN APP_TRANSFER_REQUEST.idempotency_key IS 'Khoa chong trung lap — dam bao 1 giao dich chi duoc xu ly 1 lan. Vi du: APP_TRANSFER:FT202605040007';
COMMENT ON COLUMN APP_TRANSFER_REQUEST.debit_account_no IS 'So tai khoan bi tru tien';
COMMENT ON COLUMN APP_TRANSFER_REQUEST.amount IS 'So tien chuyen (don vi: VND). Phai lon hon 0';
COMMENT ON COLUMN APP_TRANSFER_REQUEST.status IS 'Trang thai giao dich: PROCESSING (dang xu ly), SUCCESS (thanh cong), FAILED (that bai)';
COMMENT ON COLUMN APP_TRANSFER_REQUEST.created_at IS 'Thoi diem tao ban ghi';
COMMENT ON COLUMN APP_TRANSFER_REQUEST.updated_at IS 'Thoi diem cap nhat lan cuoi';

-- Bang 2: Tai khoan phia Core Banking
-- Mo phong he thong loi cua ngan hang
CREATE TABLE CORE_ACCOUNT (
    id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_no        VARCHAR2(20)  NOT NULL UNIQUE,
    available_balance NUMBER(19, 2) NOT NULL,
    created_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT ck_core_account_balance CHECK (available_balance >= 0)
);

COMMENT ON TABLE CORE_ACCOUNT IS 'Bang tai khoan phia Core Banking — luu so du kha dung cua khach hang';
COMMENT ON COLUMN CORE_ACCOUNT.id IS 'Khoa chinh, tu tang';
COMMENT ON COLUMN CORE_ACCOUNT.account_no IS 'So tai khoan duy nhat cua khach hang. Vi du: 100000001';
COMMENT ON COLUMN CORE_ACCOUNT.available_balance IS 'So du kha dung (VND). Khong duoc am (>= 0). Seed: 10,000,000';
COMMENT ON COLUMN CORE_ACCOUNT.created_at IS 'Thoi diem tao tai khoan';
COMMENT ON COLUMN CORE_ACCOUNT.updated_at IS 'Thoi diem cap nhat so du lan cuoi';

-- Bang 3: Nhat ky tru tien phia Core Banking
-- Moi lan Core tru tien se ghi 1 dong vao day
CREATE TABLE CORE_DEBIT_LOG (
    id                    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_ref          CHAR(16)       NOT NULL,
    core_idempotency_key  VARCHAR2(128)  NOT NULL,
    account_no            VARCHAR2(20)   NOT NULL,
    amount                NUMBER(19, 2)  NOT NULL,
    created_at            TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT uq_core_debit_idempotency_key UNIQUE (core_idempotency_key),
    CONSTRAINT ck_core_debit_amount CHECK (amount > 0)
);

COMMENT ON TABLE CORE_DEBIT_LOG IS 'Nhat ky tru tien phia Core — moi lan tru tien thanh cong se ghi 1 dong. Dung de doi soat (reconciliation)';
COMMENT ON COLUMN CORE_DEBIT_LOG.id IS 'Khoa chinh, tu tang';
COMMENT ON COLUMN CORE_DEBIT_LOG.business_ref IS 'Ma tham chieu nghiep vu. Dung CHAR(16) co tinh de tao bug padding — khi debug nhin giong nhau nhung byte khac nhau';
COMMENT ON COLUMN CORE_DEBIT_LOG.core_idempotency_key IS 'Khoa chong trung lap phia Core. Vi du: CORE_DEBIT:FT202605040007. Neu key da ton tai, Core se bo qua lenh tru tien';
COMMENT ON COLUMN CORE_DEBIT_LOG.account_no IS 'So tai khoan bi tru tien';
COMMENT ON COLUMN CORE_DEBIT_LOG.amount IS 'So tien da tru (VND)';
COMMENT ON COLUMN CORE_DEBIT_LOG.created_at IS 'Thoi diem Core thuc hien tru tien';
