
DELETE FROM BACKEND_DEBUG.CORE_DEBIT_LOG
WHERE 1 = 1;

DELETE FROM BACKEND_DEBUG.APP_TRANSFER_REQUEST
WHERE 1 = 1;

UPDATE BACKEND_DEBUG.CORE_ACCOUNT
SET available_balance = 10000000
WHERE account_no = '100000001';

COMMIT;